### ISSUE TITLE
Image upload path

### ISSUE THREAD

**Issue by frank2002** [Nidhushan/TimeBanking#22]
> root@9fefce277886:~/TimeBanking/Time_Banking# python manage.py runserver
> Watching for file changes with StatReloader
> Performing system checks...
> 
> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.12/threading.py", line 1012, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/local/lib/python3.12/site-packages/django/utils/autoreload.py", line 64, in wrapper
>     fn(*args, **kwargs)
>   File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
>     self.check(display_num_errors=True)
>   File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 563, in check
>     raise SystemCheckError(msg)
> django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:
> 
> ERRORS:
> Time_Banking.Listing.image: (fields.E202) ImageField's 'upload_to' argument must be a relative path, not an absolute path.
>         HINT: Remove the leading slash.
> Time_Banking.User.picture: (fields.E202) ImageField's 'upload_to' argument must be a relative path, not an absolute path.
>         HINT: Remove the leading slash.
> 
> System check identified 2 issues (0 silenced).

[#71](https://github.com/Nidhushan/TimeBanking/blob/51a9f40f02e56a55e296e718df4afab787dcde4e/Time_Banking/Time_Banking/models.py#L71)

**Comment by Nidhushan** [comment]
I was having this error as well. It looks like the change was in the recent push - Profile creation backend.

File - models.py
line 71, 45. Removing the leading / in the paths will work - "upload_to='/static/images/user'"
