### ISSUE TITLE
All profile-related fields should be optional

### ISSUE THREAD

**Issue by austinhuang0131** [Nidhushan/TimeBanking#35]
It is in my opinion that all of them should be optional. If display name is not provided then the username should take its place.

Although our current process works, it requires us to code the "edit profile" part separately and it's kind of weird. I propose that we

1. Commit the user to the database upon finishing verification
2. Redirect them to a generic "edit profile" page, so that we don't need to code a "create" page

**Comment by tanaya09** [comment]
I have made all the profile related fields optional except "Name"
