### ISSUE TITLE
Some question regarding to edit-listing

### ISSUE THREAD

**Issue by frank2002** [Nidhushan/TimeBanking#87]
## Forbid changing the list after confirming the acceptance of another user

If a listing is confirmed to accept by another user, in my point of view, it should be no longer changed. 

Or at least **only** the description part can be changed. Since we do not have snapshot function, the simplest way is just to forbid the change.

## Preserve saved info
When editting the listing, some fields should be preserved. 

For now, locally, the category field and image field will be missing. The user need to fill them again

_We can discuss in the meeting._

**Comment by austinhuang0131** [comment]
for the former, too late to discuss for the final presentation

for the latter, the commit that populates the form values is https://github.com/Nidhushan/TimeBanking/commit/6d5ccdb86dee3607d44ed2b65f84a5c6baa061da. i'm not too sure about how to deal with the images field
